### ISSUE TITLE
Outputting different variables?

### ISSUE THREAD

**Issue by AndrewILWilliams** [aperezhortal/pySPEEDY#5]
Hi there,

Just came across this very cool package! Franco gave a talk at my department yesterday and I was hoping someone had made a python wrapper for Speedy! :D 

I have one question. In the collab notebook, everything works great, except for the fact that i can't output non-standard variables.

For example, see this screenshot below.

![image](https://user-images.githubusercontent.com/56925856/203967186-a200b717-de61-4b75-b0f6-ca8388e76123.png)

Am I doing something wrong here?

Cheers
Andrew

**Comment by AndrewWilliams3142** [comment]
Should also note that the precipitation vars also don't exist in the `model_checkpoint` 
![image](https://user-images.githubusercontent.com/56925856/203967278-c85a38db-3eb7-415b-924c-51e275b98a24.png)

**Comment by aperezhortal** [comment]
Hi @AndrewWilliams3142 !

Thank you for using PySpeedy! I think that I know what the problem is... the keyword argument is being ignored:
https://github.com/aperezhortal/pySPEEDY/blob/f20d976f5552afd334294b5e38af8044f6292181/pyspeedy/callbacks.py#L173

I suspect that other callbacks have the same issue... 


I will take a look at it as soon as possible.

**Comment by aperezhortal** [comment]
Better late than never. [3feb4da](https://github.com/aperezhortal/pySPEEDY/commit/3feb4dada72ca277667841169f5accbe779fc9d6) should fix this issue.
